[project]
name = "workout-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rachel Cieslik", email = "rachelmarielizabeth@yahoo.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.2",
    "polars>=1.44.2",
    "ruff>=0.16.7",
    "ty>=0.0.81",
]

[project.scripts]
workout-tracker = "workout_tracker:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
